### ISSUE TITLE
Develop v0.2, Usability

### ISSUE THREAD

**Issue by pbayer** [JuliaActors/Actors.jl#10]
Version 0.2 is all about **usability** in order to enable application development. `Actors` 0.2 should be supersede `YAActL` 0.2.1

## Actor API

- [x] Actor API, issue #8 closed,

## Behavior Improvements

- [x] check closure as an alternative to `Func`, (see comment below)
- [x] integrate closure into `Func` and make `Func` executable, (see comment below),
- [x] make the behavior work in the current world age,
- [x] call the behavior directly with the message,
- [x] rename `Func` to `Bhv` (more to the point),
- [x] enable object-oriented approach, issue #14 

## Registry 
- [x] Actor registry, issue #9 closed,

## Finish v0.2

- [x] Actors basic interface, issue #12 closed 
- [x] implement diagnostics (see comment below),
- [x] complete documentation,
- [x] application specific examples,
- [x] test coverage,
- [x] register 0.2,
- [x] announce on Discourse

**Comment by pbayer** [comment]
## Implement actor diagnostics

Enhance `Diag` and `diag` to check if an actor is ok. If it has failed thus we get a stack trace even from remote channels. See also [issue 16 to YAActL](https://github.com/JuliaActors/YAActL.jl/issues/16).

**Comment by pbayer** [comment]
## Register Actors v0.1.5

@JuliaRegistrator register

Release notes:

- renamed `Func` to `Bhv` (more appropriate)

**Comment by pbayer** [comment]
## Register `Actors` v0.2

@JuliaRegistrator register

Release notes:

- improved **interface**,
- flexibility in expressing actor behavior with **partial function application** and **functors**,
- actor **protocol** improved,
- complete **documentation** with more **examples**.

**Comment by pbayer** [comment]
See the [announcement on Discourse](https://discourse.julialang.org/t/ann-actors-0-2-genservers-and-guards/52056).
