### ISSUE TITLE
Improve Supervision

### ISSUE THREAD

**Issue by pbayer** [JuliaActors/Actors.jl#22]
This is a collection of **various improvements** to supervision (implemented in issue #16):

- [x] remote actor restart on the same PIDs,
- [x] supervision of registered actors (see comment below),
- [x] identify supervised actors by name (see comment below),
- [x] make the supervisor API thoroughly work with registered actor names,
- [ ] functionality to kill a running actor,
- [ ] ensure an actor is shutdown in a given timeframe,
- [ ] ensure a supervisor is restarted (with childs) in a given timeframe,

## Task supervision

I have to look further into the following: 

- [ ] How to tackle (long) running tasks at supervisor shutdown,
- [ ] How about tasks running on remote processes?

**Comment by pbayer** [comment]
## Supervision of registered actors

If remote actors communicate with each other over `RemoteChannel`s, several copies of an actor link may exist on different workers. After restart of an actor those links get out of sync!

I that case those actors must be registered and the supervisor supervises a registered actor **name** and **updates the link for that name** after actor restart. The registry then is the one place having a current link to the remote actor.

### Note

It is better **not to enforce** remote actor registration since in a strictly hierarchical network topology with the supervisor running at the root node this is not strictly needed.

**Comment by pbayer** [comment]
## Identify supervised actors by name

Currently after actor restart due to a node failure the supervisor gives a warning `restarting @unknown on pid x`. This makes no sense for diagnosis.

Therefore actors must be identifiable and be identified either by their `Proquint` string or by their registered name. Three changes are necessary to the:

- [ ] `info` function,
- [ ] `Child` struct,
- [ ] error-handling warnings
